version: '3.8'

services:
  verify:
    build:
      context: ./diagnostics
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - APP_PASSWORD=${APP_PASSWORD}
      - PASSWORD_HASH=${PASSWORD_HASH}
    command: verify_env.py

  test-auth:
    build:
      context: ./diagnostics
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - APP_PASSWORD=${APP_PASSWORD}
      - PASSWORD_HASH=${PASSWORD_HASH}
    command: test_auth.py